name: ci-test

on:
  push:
    branches: [ dev  ]
  pull_request:
    branches: [ dev, config/github_workflow]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
  
    - name: Check out code into go module directory
      uses: actions/checkout@v2

    - name: migrate the db
      run: make migrateup

    - name: Test
      run: make test
