name: Test on CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  test:
    name: Test-job
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
  
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Migrate the db
      run: make migrateup

    - name: Run tests
      run: make test
